-- migration 006: Phase 5 — PPTX/PDF presentation set items
--
-- Adds slide_count to media table for MediaKind::Presentation rows.
-- slide_count stores the number of PNG slides generated by LibreOffice conversion.
-- NULL for all existing image/video rows.

ALTER TABLE media ADD COLUMN slide_count INTEGER;
